language: objective-c
osx_image: xcode7

xcode_project: WolframAlpha.xcodeproj
xcode_scheme: WolframAlpha

branches:
  only:
    - master
    - /^deploy-.*$/

notifications:
  email: false

before_install:
  - gem install xcpretty -N
script:
  - set -o pipefail
  - xcodebuild -project WolframAlpha.xcodeproj -scheme "WolframAlpha" -sdk iphonesimulator
    -destination "platform=iOS Simulator,name=iPhone 6" ONLY_ACTIVE_ARCH=NO  test | xcpretty -c
  - pod lib lint --quick
